security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\UserModule\User:
            algorithm: bcrypt
            cost: 12

    providers:
        app_user_provider:
            entity:
                class: App\Entity\UserModule\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            access_denied_handler: App\Controller\UserModule\AccessDeniedController
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: user_dashboard
                enable_csrf: true
                username_parameter: '_username'
                password_parameter: '_password'
                csrf_parameter: '_csrf_token'
                csrf_token_id: 'authenticate'
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: user_dashboard
                always_remember_me: true
            logout:
                path: logout
                target: login
                invalidate_session: true


    access_control:
        - { path: ^/signup, roles: PUBLIC_ACCESS }
        - { path: ^/tosignup, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/admin/google/auth, roles: PUBLIC_ACCESS }
        - { path: ^/calendar-callback, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/admindashboard, roles: ROLE_ADMIN }
        - { path: ^/eventplanner, roles: ROLE_EVENTPLANNER }
        - { path: ^/instructor, roles: ROLE_INSTRUCTOR }
        - { path: ^/event/home, roles: ROLE_CLIENT }
        - { path: ^/partner, roles: [ ROLE_ADMIN, ROLE_EVENTPLANNER ] }
        - { path: ^/workshop/new, roles: [ ROLE_ADMIN, ROLE_EVENTPLANNER, ROLE_INSTRUCTOR ] }
        - { path: ^/workshop/front/\d+, roles: ROLE_CLIENT }
        - { path: ^/workshop/front, roles: ROLE_CLIENT }
        - { path: ^/workshop, roles: [ ROLE_ADMIN, ROLE_EVENTPLANNER, ROLE_CLIENT, ROLE_INSTRUCTOR ] }
        - { path: ^/session, roles: [ ROLE_ADMIN, ROLE_EVENTPLANNER, ROLE_INSTRUCTOR ] }
        - { path: ^/sidenav/userdash, roles: [ ROLE_ADMIN, ROLE_EVENTPLANNER, ROLE_CLIENT, ROLE_INSTRUCTOR ] }
        - { path: ^/user/profile, roles: [ ROLE_ADMIN, ROLE_EVENTPLANNER, ROLE_CLIENT, ROLE_INSTRUCTOR ] }
        - { path: ^/sidenav/profile, roles: [ ROLE_ADMIN, ROLE_EVENTPLANNER, ROLE_CLIENT, ROLE_INSTRUCTOR ] }
        - { path: ^/user/account_security, roles: [ ROLE_ADMIN, ROLE_EVENTPLANNER, ROLE_CLIENT, ROLE_INSTRUCTOR ] }
        - { path: ^/app_home, roles: [ ROLE_ADMIN, ROLE_EVENTPLANNER, ROLE_CLIENT, ROLE_INSTRUCTOR ] }
        - { path: ^/, roles: [ ROLE_ADMIN, ROLE_EVENTPLANNER, ROLE_CLIENT, ROLE_INSTRUCTOR ] }
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: bcrypt
                cost: 4